# Generated by Django 4.2.21 on 2025-09-28 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('not_started', '未开启'), ('in_progress', '进行中'), ('blocked', '遇到阻碍'), ('resolved', '已解决')], default='not_started', max_length=20, verbose_name='状态')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '目标',
                'verbose_name_plural': '目标',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立时间')),
                ('status', models.CharField(choices=[('not_done', '未完成'), ('done', '已完成')], default='not_done', max_length=20, verbose_name='状态')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='goal_app.goal', verbose_name='关联目标')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/%d/', verbose_name='附件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='goal_app.task')),
            ],
            options={
                'verbose_name': '任务附件',
                'verbose_name_plural': '任务附件',
            },
        ),
        migrations.CreateModel(
            name='GoalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='goal_attachments/%Y/%m/%d/', verbose_name='附件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='goal_app.goal')),
            ],
            options={
                'verbose_name': '目标附件',
                'verbose_name_plural': '目标附件',
            },
        ),
    ]
