# Generated by Django 4.2.21 on 2025-10-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0003_alter_goal_description_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_time'], 'verbose_name': '目标', 'verbose_name_plural': '目标'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_time'], 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.CharField(choices=[('very_high', '极高重要性'), ('high', '高重要性'), ('medium', '中等重要性'), ('low', '低重要性'), ('very_low', '极低/无关重要性')], default='medium', max_length=20, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='goal',
            name='urgency',
            field=models.CharField(choices=[('very_high', '极急'), ('high', '高紧急性'), ('medium', '中等紧急性'), ('low', '低紧急性'), ('very_low', '极低/无时间限制')], default='medium', max_length=20, verbose_name='紧急性'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('very_high', '极高重要性'), ('high', '高重要性'), ('medium', '中等重要性'), ('low', '低重要性'), ('very_low', '极低/无关重要性')], default='medium', max_length=20, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='task',
            name='urgency',
            field=models.CharField(choices=[('very_high', '极急'), ('high', '高紧急性'), ('medium', '中等紧急性'), ('low', '低紧急性'), ('very_low', '极低/无时间限制')], default='medium', max_length=20, verbose_name='紧急性'),
        ),
    ]
