# Generated by Django 4.2.21 on 2025-10-27 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goal_app', '0004_alter_goal_options_alter_task_options_goal_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_time'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='goalattachment',
            options={'verbose_name': 'Goal Attachment', 'verbose_name_plural': 'Goal Attachments'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_time'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'verbose_name': 'Task Attachment', 'verbose_name_plural': 'Task Attachments'},
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_app_goals', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='priority',
            field=models.CharField(choices=[('very_high', 'very_high'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('very_low', 'very_low')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('resolved', 'Resolved')], default='not_started', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Goal Title'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='urgency',
            field=models.CharField(choices=[('very_high', 'very_high'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('very_low', 'very_low')], default='medium', max_length=20, verbose_name='Urgency'),
        ),
        migrations.AlterField(
            model_name='goalattachment',
            name='file',
            field=models.FileField(upload_to='goal_attachments/%Y/%m/%d/', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Task Creator'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_app_tasks', to='goal_app.goal', verbose_name='Associated Goal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Task Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('very_high', 'very_high'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('very_low', 'very_low')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_done', 'Not Done'), ('done', 'Done')], default='not_done', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.CharField(choices=[('very_high', 'very_high'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('very_low', 'very low')], default='medium', max_length=20, verbose_name='Urgency'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to='task_attachments/%Y/%m/%d/', verbose_name='attachment'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tag Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_app_tags', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'creator')},
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='goals', to='goal_app.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='goal_app.tag', verbose_name='Tags'),
        ),
    ]
