# Generated by Django 4.2.21 on 2025-10-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0005_alter_goal_options_alter_goalattachment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_at'], 'verbose_name': 'add a tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
