# Generated by Django 4.2.21 on 2025-08-31 07:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='单词')),
                ('explanation', models.TextField(verbose_name='单词解释')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '英文单词',
                'verbose_name_plural': '英文单词',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnglishWordMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='word_media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'mp4', 'avi', 'mov', 'pdf', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='附件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='main_app.englishword', verbose_name='关联单词')),
            ],
            options={
                'verbose_name': '单词多媒体文件',
                'verbose_name_plural': '单词多媒体文件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
