# Generated by Django 4.2.21 on 2025-09-29 06:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishword',
            options={'ordering': ['-created_at'], 'verbose_name': 'English Word', 'verbose_name_plural': 'Vocabularies'},
        ),
        migrations.AlterModelOptions(
            name='englishwordmedia',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'media File', 'verbose_name_plural': 'media Files'},
        ),
        migrations.AlterField(
            model_name='englishword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='explanation',
            field=models.TextField(verbose_name='Word Explanation'),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Words'),
        ),
        migrations.AlterField(
            model_name='englishwordmedia',
            name='file',
            field=models.FileField(upload_to='word_media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'mp4', 'avi', 'mov', 'pdf', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='attached File'),
        ),
        migrations.AlterField(
            model_name='englishwordmedia',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='main_app.englishword', verbose_name='associated Word'),
        ),
    ]
