# Generated by Django 4.2.21 on 2025-10-27 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_tag_englishword_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishword',
            options={'ordering': ['-created_at'], 'verbose_name': 'Words', 'verbose_name_plural': 'Words'},
        ),
        migrations.AlterField(
            model_name='englishword',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='english_words', to='main_app.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='englishwordmedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created Time'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='tag Name'),
        ),
    ]
