# Generated by Django 4.2.21 on 2025-10-27 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_alter_englishword_options_alter_englishword_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishword',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='main_app_english_words', to='main_app.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_app_tags', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
