# Generated by Django 4.2.21 on 2025-10-27 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_alter_englishword_tags_alter_tag_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishword',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_app_english_words', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
