# Generated by Django 4.2.21 on 2025-10-27 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_alter_englishword_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishword',
            options={'ordering': ['-created_at'], 'verbose_name': 'English Word', 'verbose_name_plural': 'English Words'},
        ),
        migrations.AlterField(
            model_name='englishword',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='english_words', to='main_app.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='englishwordmedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_app_tags', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='标签名称'),
        ),
    ]
