# Generated by Django 4.2.21 on 2026-03-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_alter_englishword_options_alter_englishword_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='englishword',
            options={'ordering': ['-created_at'], 'verbose_name': 'English Word', 'verbose_name_plural': 'Vocabulary'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_app_tags', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tag Name'),
        ),
        migrations.CreateModel(
            name='StoryEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_snapshots', models.JSONField(default=list, help_text='Snapshot of [{title, explanation}] at send time', verbose_name='Word Snapshots')),
                ('story_content', models.TextField(verbose_name='Story Content')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('recipient_emails', models.JSONField(default=list, verbose_name='Recipient Emails')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_emails', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('words', models.ManyToManyField(blank=True, related_name='story_emails', to='main_app.englishword', verbose_name='Words Used')),
            ],
            options={
                'verbose_name': 'Story Email',
                'verbose_name_plural': 'Story Emails',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='Timezone')),
                ('send_times', models.JSONField(default=list, help_text='List of "HH:MM" strings, e.g. ["08:00", "18:00"]', verbose_name='Send Times')),
                ('words_per_email', models.PositiveIntegerField(default=3, verbose_name='Words Per Email')),
                ('extra_recipients', models.JSONField(default=list, help_text='Up to 3 additional email addresses', verbose_name='Extra Recipients')),
                ('story_language', models.CharField(choices=[('english', 'English'), ('bilingual', 'Bilingual (English + Chinese)')], default='english', max_length=20, verbose_name='Story Language')),
                ('exclude_word_ids', models.JSONField(default=list, help_text='Word IDs to exclude from random selection', verbose_name='Excluded Word IDs')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_schedule', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Schedule Config',
                'verbose_name_plural': 'Email Schedule Configs',
            },
        ),
    ]
